### ISSUE TITLE
paper or program introduction

### ISSUE THREAD

**Issue by wangtianrui** [YanjueSong/Improved-CEM-samples#1]
Hello Yanjue, 

According to the effect picture, your work seems to enhance harmonics in the case of noise.  It looks like a nice job!
I am very interested in it. 
May I ask if there is any relevant pre-published paper?

**Comment by YanjueSong** [comment]
Hello. Thanks for your interest! 
Indeed, this is the samples of a journal paper. However, we just made the submission so couldn't share a pre-print yet. We'll get in touch once the pre-print is available :)

**Comment by wangtianrui** [comment]
Thank you very much.Looking forward to your good news.
